# ** INSURANCE CLAIM PREDICTION **

# PROBLEM STATEMENT:
  The insurance marketing team aims to identify which customers are most likely to purchase an insurance product. By leveraging a predictive model, the team can prioritize high-potential leads, optimize marketing efforts, and allocate resources more effectively. The goal is to enhance conversion rates while reducing acquisition costs.

# 1. IMPORTING LIBRARIES

In [1]:
#Importing pandas library to perform many task in dataset.
import pandas as pd

#Importing numpy library used to perform mathematical operation and scientific computing.
import numpy as np

#Importing matplotlib library used to create graphs,chart, and other visualization
import matplotlib.pyplot as plt

#Importing seaborn library used to perform making stastical graphics
import seaborn as sns

#Importing warnings for disable warnings from the code
import warnings
#to ignore the warnings
warnings.filterwarnings('ignore')


# MinMaxScaler for feature scaling to bring values within a specific range
from sklearn.preprocessing import MinMaxScaler

# Importing train_test_split for splitting data into training and testing sets for model evaluation
from sklearn.model_selection import train_test_split

# Importing SMOTE from imblearn
from imblearn.over_sampling import SMOTE

# Importing LogisticRegression
from sklearn.linear_model import LogisticRegression

# Importing DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

# Importing an ensemble model RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

# Importing an advanced boosting model GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier

# Importing KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

# Importing GridSearchCV for Hyperparameter tuning
from sklearn.model_selection import GridSearchCV

# Importing RandomizedSearchCV for hyperparameter tuning using randomized search
from sklearn.model_selection import RandomizedSearchCV

# Importing Multi-layer Perceptron (MLP) Classifier
from sklearn.neural_network import MLPClassifier

# Importing performance metrics for model evaluation
# accuracy_score,confusion_matrix,classification_report,etc.
from sklearn.metrics import *

# 2. LOADING THE DATASET

In [5]:
Data = pd.read_csv('../data/train.csv')
Data

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,1488013,0,3,1,10,0,0,0,0,0,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,...,4,4,3,8,0,1,0,0,0,0

In [7]:
Data.drop(columns="id", inplace=True)

In [8]:
pd.set_option("display.max_columns",None)
Data

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_01_cat,ps_car_02_cat,ps_car_03_cat,ps_car_04_cat,ps_car_05_cat,ps_car_06_cat,ps_car_07_cat,ps_car_08_cat,ps_car_09_cat,ps_car_10_cat,ps_car_11_cat,ps_car_11,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03,ps_calc_04,ps_calc_05,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,2,2,5,1,0,0,1,0,0,0,0,0,0,0,11,0,1,0,0.7,0.2,0.718070,10,1,-1,0,1,4,1,0,0,1,12,2,0.400000,0.883679,0.370810,3.605551,0.6,0.5,0.2,3,1,10,1,10,1,5,9,1,5,8,0,1,1,0,0,1
1,0,1,1,7,0,0,0,0,1,0,0,0,0,0,0,3,0,0,1,0.8,0.4,0.766078,11,1,-1,0,-1,11,1,1,2,1,19,3,0.316228,0.618817,0.388716,2.449490,0.3,0.1,0.3,2,1,9,5,8,1,7,3,1,1,9,0,1,1,0,1,0
2,0,5,4,9,1,0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.0,0.0,-1.000000,7,1,-1,0,-1,14,1,1,2,1,60,1,0.316228,0.641586,0.347275,3.316625,0.5,0.7,0.1,2,2,9,1,8,2,7,4,2,7,7,0,1,1,0,1,0
3,0,0,1,2,0,0,1,0,0,0,0,0,0,0,0,8,1,0,0,0.9,0.2,0.580948,7,1,0,0,1,11,1,1,3,1,104,1,0.374166,0.542949,0.294958,2.000000,0.6,0.9,0.1,2,4,7,1,8,4,2,2,2,4,9,0,0,0,0,0,0
4,0,0,2,0,1,0,1,0,0,0,0,0,0,0,0,9,1,0,0,0.7,0.6,0.840759,11,1,-1,0,-1,14,1,1,2,1,82,3,0.316070,0.565832,0.365103,2.000000,0.4,0.6,0.0,2,2,6,3,10,2,12,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,0,3,1,10,0,0,0,0,0,1,0,0,0,0,0,13,1,0,0,0.5,0.3,0.692820,10,1,-1,0,1,1,1,1,0,1,31,3,0.374166,0.684631,0.385487,2.645751,0.4,0.5,0.3,3,0,9,0,9,1,12,4,1,9,6,0,1,1,0,1,1
595208,0,5,1,3,0,0,0,0,0,1,0,0,0,0,0,6,1,0,0,0.9,0.7,1.382027,9,1,-1,0,-1,15,0,0,2,1,63,2,0.387298,0.972145,-1.000000,3.605551,0.2,0.2,0.0,2,4,8,6,8,2,12,4,1,3,8,1,0,1,0,1,1
595209,0,1,1,10,0,0,1,0,0,0,0,0,0,0,0,12,1,0,0,0.9,0.2,0.659071,7,1,-1,0,-1,1,1,1,2,1,31,3,0.397492,0.596373,0.398748,1.732051,0.4,0.0,0.3,3,2,7,4,8,0,10,3,2,2,6,0,0,1,0,0,0
595210,0,5,2,3,1,0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.9,0.4,0.698212,11,1,-1,0,-1,11,1,1,2,1,101,3,0.374166,0.764434,0.384968,3.162278,0.0,0.7,0.0,4,0,9,4,9,2,11,4,1,4,2,0,1,1,1,0,0
595211,0,0,1,8,0,0,1,0,0,0,0,0,0,0,0,7,1,0,0,0.1,0.2,-1.000000,7,0,-1,0,-1,0,1,0,2,1,34,2,0.400000,0.932649,0.378021,3.741657,0.4,0.0,0.5,2,3,10,4,10,2,5,4,4,3,8,0,1,0,0,0,0

# 3.BASIC CHECKS

In [9]:
#visualizing the first 10 rows of the data
Data.head(10)

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_01_cat,ps_car_02_cat,ps_car_03_cat,ps_car_04_cat,ps_car_05_cat,ps_car_06_cat,ps_car_07_cat,ps_car_08_cat,ps_car_09_cat,ps_car_10_cat,ps_car_11_cat,ps_car_11,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03,ps_calc_04,ps_calc_05,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,2,2,5,1,0,0,1,0,0,0,0,0,0,0,11,0,1,0,0.7,0.2,0.718070,10,1,-1,0,1,4,1,0,0,1,12,2,0.400000,0.883679,0.370810,3.605551,0.6,0.5,0.2,3,1,10,1,10,1,5,9,1,5,8,0,1,1,0,0,1
1,0,1,1,7,0,0,0,0,1,0,0,0,0,0,0,3,0,0,1,0.8,0.4,0.766078,11,1,-1,0,-1,11,1,1,2,1,19,3,0.316228,0.618817,0.388716,2.449490,0.3,0.1,0.3,2,1,9,5,8,1,7,3,1,1,9,0,1,1,0,1,0
2,0,5,4,9,1,0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.0,0.0,-1.000000,7,1,-1,0,-1,14,1,1,2,1,60,1,0.316228,0.641586,0.347275,3.316625,0.5,0.7,0.1,2,2,9,1,8,2,7,4,2,7,7,0,1,1,0,1,0
3,0,0,1,2,0,0,1,0,0,0,0,0,0,0,0,8,1,0,0,0.9,0.2,0.580948,7,1,0,0,1,11,1,1,3,1,104,1,0.374166,0.542949,0.294958,2.000000,0.6,0.9,0.1,2,4,7,1,8,4,2,2,2,4,9,0,0,0,0,0,0
4,0,0,2,0,1,0,1,0,0,0,0,0,0,0,0,9,1,0,0,0.7,0.6,0.840759,11,1,-1,0,-1,14,1,1,2,1,82,3,0.316070,0.565832,0.365103,2.000000,0.4,0.6,0.0,2,2,6,3,10,2,12,3,1,1,3,0,0,0,1,1,0
5,0,5,1,4,0,0,0,0,0,1,0,0,0,0,0,6,1,0,0,0.9,1.8,2.332649,10,0,-1,0,0,14,1,1,0,1,104,2,0.445982,0.879049,0.406202,3.000000,0.7,0.8,0.4,3,1,8,2,11,3,8,4,2,0,9,0,1,0,1,1,1
6,0,2,1,3,1,0,0,1,0,0,0,0,0,0,0,8,1,0,0,0.6,0.1,0.617454,6,1,-1,0,1,11,1,1,0,1,99,2,0.316228,0.639683,0.368782,3.162278,0.2,0.6,0.5,2,2,8,1,8,3,10,3,0,0,10,0,1,0,0,1,0
7,0,5,1,4,0,0,1,0,0,0,0,0,0,0,0,13,1,0,0,0.7,0.4,0.607248,11,1,0,0,0,11,1,1,2,1,30,3,0.446990,0.900574,0.374833,3.316625,0.1,0.5,0.1,1,2,7,1,6,1,13,7,1,3,6,1,0,1,0,1,0
8,0,5,1,3,1,0,0,0,1,0,0,0,0,0,0,6,1,0,0,0.9,0.7,0.901388,10,1,-1,0,1,14,1,1,0,1,68,3,0.400000,0.780641,0.407431,2.828427,0.9,0.8,0.6,3,1,7,3,9,4,11,4,2,1,5,0,1,0,0,0,1
9,1,1,1,2,0,0,0,1,0,0,0,0,0,0,0,4,0,0,1,0.9,1.4,2.316652,11,0,0,1,0,14,1,1,2,1,104,2,0.447214,1.458184,0.390256,3.605551,0.7,0.8,0.8,2,2,8,2,9,1,11,3,5,0,6,0,1,0,0,1,0

In [10]:
#visualizing last 10 row of the data
Data.tail(10)

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_01_cat,ps_car_02_cat,ps_car_03_cat,ps_car_04_cat,ps_car_05_cat,ps_car_06_cat,ps_car_07_cat,ps_car_08_cat,ps_car_09_cat,ps_car_10_cat,ps_car_11_cat,ps_car_11,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03,ps_calc_04,ps_calc_05,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
595202,0,4,1,3,0,0,0,1,0,0,0,0,0,0,0,2,1,0,0,0.5,0.0,0.366572,9,1,0,0,1,11,1,1,0,1,53,2,0.447214,0.744248,0.377492,2.449490,0.7,0.5,0.0,2,2,7,3,8,2,7,11,6,2,6,0,1,1,0,1,0
595203,0,3,2,3,1,0,0,1,0,0,0,0,0,0,0,5,0,1,0,0.9,1.4,1.939233,7,1,1,0,0,14,1,0,2,1,72,3,0.400000,1.135400,0.350428,3.741657,0.8,0.6,0.2,4,1,7,2,10,1,11,5,2,1,6,0,0,0,0,0,0
595204,0,1,2,2,1,0,0,1,0,0,0,0,0,0,0,11,1,0,0,0.7,0.3,0.704894,6,1,-1,0,-1,6,1,1,2,1,27,3,0.374166,0.795351,0.390768,3.605551,0.5,0.5,0.5,2,3,6,3,8,1,3,3,1,3,9,0,1,0,0,1,0
595205,0,0,3,6,1,0,0,1,0,0,0,0,0,0,0,7,1,0,0,0.4,0.5,0.904848,5,1,0,0,1,6,1,1,2,1,26,3,0.374166,0.603399,0.320468,2.645751,0.8,0.2,0.5,4,1,9,4,8,3,12,7,1,2,6,1,0,1,0,0,0
595206,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,2,1,0,0,0.9,0.2,0.653835,7,1,-1,8,-1,13,1,1,2,1,20,3,0.447214,0.903506,0.429535,3.000000,0.1,0.8,0.8,3,2,8,3,10,2,11,8,0,1,7,0,1,1,0,0,0
595207,0,3,1,10,0,0,0,0,0,1,0,0,0,0,0,13,1,0,0,0.5,0.3,0.692820,10,1,-1,0,1,1,1,1,0,1,31,3,0.374166,0.684631,0.385487,2.645751,0.4,0.5,0.3,3,0,9,0,9,1,12,4,1,9,6,0,1,1,0,1,1
595208,0,5,1,3,0,0,0,0,0,1,0,0,0,0,0,6,1,0,0,0.9,0.7,1.382027,9,1,-1,0,-1,15,0,0,2,1,63,2,0.387298,0.972145,-1.000000,3.605551,0.2,0.2,0.0,2,4,8,6,8,2,12,4,1,3,8,1,0,1,0,1,1
595209,0,1,1,10,0,0,1,0,0,0,0,0,0,0,0,12,1,0,0,0.9,0.2,0.659071,7,1,-1,0,-1,1,1,1,2,1,31,3,0.397492,0.596373,0.398748,1.732051,0.4,0.0,0.3,3,2,7,4,8,0,10,3,2,2,6,0,0,1,0,0,0
595210,0,5,2,3,1,0,0,0,1,0,0,0,0,0,0,12,1,0,0,0.9,0.4,0.698212,11,1,-1,0,-1,11,1,1,2,1,101,3,0.374166,0.764434,0.384968,3.162278,0.0,0.7,0.0,4,0,9,4,9,2,11,4,1,4,2,0,1,1,1,0,0
595211,0,0,1,8,0,0,1,0,0,0,0,0,0,0,0,7,1,0,0,0.1,0.2,-1.000000,7,0,-1,0,-1,0,1,0,2,1,34,2,0.400000,0.932649,0.378021,3.741657,0.4,0.0,0.5,2,3,10,4,10,2,5,4,4,3,8,0,1,0,0,0,0

In [11]:
Data.columns

Index(['target', 'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03', 'ps_ind_04_cat',
       'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin', 'ps_ind_08_bin',
       'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin', 'ps_ind_12_bin',
       'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15', 'ps_ind_16_bin',
       'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01', 'ps_reg_02', 'ps_reg_03',
       'ps_car_01_cat', 'ps_car_02_cat', 'ps_car_03_cat', 'ps_car_04_cat',
       'ps_car_05_cat', 'ps_car_06_cat', 'ps_car_07_cat', 'ps_car_08_cat',
       'ps_car_09_cat', 'ps_car_10_cat', 'ps_car_11_cat', 'ps_car_11',
       'ps_car_12', 'ps_car_13', 'ps_car_14', 'ps_car_15', 'ps_calc_01',
       'ps_calc_02', 'ps_calc_03', 'ps_calc_04', 'ps_calc_05', 'ps_calc_06',
       'ps_calc_07', 'ps_calc_08', 'ps_calc_09', 'ps_calc_10', 'ps_calc_11',
       'ps_calc_12', 'ps_calc_13', 'ps_calc_14', 'ps_calc_15_bin',
       'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin', 'ps_calc_19_bin',
       'ps_calc_20_bin'],
      dtype='str')

In [12]:
#checking the index of the data
Data.index

RangeIndex(start=0, stop=595212, step=1)

In [13]:
Data.shape

(595212, 58)

In [14]:
Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   target          595212 non-null  int64
 1   ps_ind_01       595212 non-null  int64
 2   ps_ind_02_cat   595212 non-null  int64
 3   ps_ind_03       595212 non-null  int64
 4   ps_ind_04_cat   595212 non-null  int64
 5   ps_ind_05_cat   595212 non-null  int64
 6   ps_ind_06_bin   595212 non-null  int64
 7   ps_ind_07_bin   595212 non-null  int64
 8   ps_ind_08_bin   595212 non-null  int64
 9   ps_ind_09_bin   595212 non-null  int64
 10  ps_ind_10_bin   595212 non-null  int64
 11  ps_ind_11_bin   595212 non-null  int64
 12  ps_ind_12_bin   595212 non-null  int64
 13  ps_ind_13_bin   595212 non-null  int64
 14  ps_ind_14       595212 non-null  int64
 15  ps_ind_15       595212 non-null  int64
 16  ps_ind_16_bin   595212 non-null  int64
 17  ps_ind_17_bin   595212 non-null  int64
 18  ps_ind_18_bin   595212 non-null  int64
 19  ps_reg_01       595212 non-null  float64
 20  ps_reg_02       595212 non-null  float64
 21  ps_reg_03       595212 non-null  float64
 22  ps_car_01_cat   595212 non-null  int64
 23  ps_car_02_cat   595212 non-null  int64
 24  ps_car_03_cat   595212 non-null  int64
 25  ps_car_04_cat   595212 non-null  int64
 26  ps_car_05_cat   595212 non-null  int64
 27  ps_car_06_cat   595212 non-null  int64
 28  ps_car_07_cat   595212 non-null  int64
 29  ps_car_08_cat   595212 non-null  int64
 30  ps_car_09_cat   595212 non-null  int64
 31  ps_car_10_cat   595212 non-null  int64
 32  ps_car_11_cat   595212 non-null  int64
 33  ps_car_11       595212 non-null  int64
 34  ps_car_12       595212 non-null  float64
 35  ps_car_13       595212 non-null  float64
 36  ps_car_14       595212 non-null  float64
 37  ps_car_15       595212 non-null  float64
 38  ps_calc_01      595212 non-null  float64
 39  ps_calc_02      595212 non-null  float64
 40  ps_calc_03      595212 non-null  float64
 41  ps_calc_04      595212 non-null  int64
 42  ps_calc_05      595212 non-null  int64
 43  ps_calc_06      595212 non-null  int64
 44  ps_calc_07      595212 non-null  int64
 45  ps_calc_08      595212 non-null  int64
 46  ps_calc_09      595212 non-null  int64
 47  ps_calc_10      595212 non-null  int64
 48  ps_calc_11      595212 non-null  int64
 49  ps_calc_12      595212 non-null  int64
 50  ps_calc_13      595212 non-null  int64
 51  ps_calc_14      595212 non-null  int64
 52  ps_calc_15_bin  595212 non-null  int64
 53  ps_calc_16_bin  595212 non-null  int64
 54  ps_calc_17_bin  595212 non-null  int64
 55  ps_calc_18_bin  595212 non-null  int64
 56  ps_calc_19_bin  595212 non-null  int64
 57  ps_calc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(48)
memory usage: 263.4 MB

In [15]:
Data.describe()

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin,ps_ind_18_bin,ps_reg_01,ps_reg_02,ps_reg_03,ps_car_01_cat,ps_car_02_cat,ps_car_03_cat,ps_car_04_cat,ps_car_05_cat,ps_car_06_cat,ps_car_07_cat,ps_car_08_cat,ps_car_09_cat,ps_car_10_cat,ps_car_11_cat,ps_car_11,ps_car_12,ps_car_13,ps_car_14,ps_car_15,ps_calc_01,ps_calc_02,ps_calc_03,ps_calc_04,ps_calc_05,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,0.036448,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,0.185304,0.000373,0.001692,0.009439,0.000948,0.012451,7.299922,0.660823,0.121081,0.153446,0.610991,0.439184,0.551102,8.295933,0.829931,-0.504899,0.725192,-0.157732,6.555340,0.910027,0.832080,1.328890,0.992136,62.215674,2.346072,0.379945,0.813265,0.276256,3.065899,0.449756,0.449589,0.449849,2.372081,1.885886,7.689445,3.005823,9.225904,2.339034,8.433590,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,0.187401,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,0.388544,0.019309,0.041097,0.096693,0.030768,0.127545,3.546042,0.473430,0.326222,0.360417,0.287643,0.404264,0.793506,2.508270,0.375716,0.788654,2.153463,0.844417,5.501445,0.347106,0.373796,0.978747,0.091619,33.012455,0.832548,0.058327,0.224588,0.357154,0.731366,0.287198,0.286893,0.287153,1.117219,1.134927,1.334312,1.414564,1.459672,1.246949,2.904597,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,1.000000,-1.000000,-1.000000,0.250619,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.400000,0.200000,0.525000,7.000000,1.000000,-1.000000,0.000000,-1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,32.000000,2.000000,0.316228,0.670867,0.333167,2.828427,0.200000,0.200000,0.200000,2.000000,1.000000,7.000000,2.000000,8.000000,1.000000,6.000000,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,0.000000,0.000000,0.700000,0.300000,0.720677,7.000000,1.000000,-1.000000,0.000000,0.000000,7.000000,1.000000,1.000000,2.000000,1.000000,65.000000,3.000000,0.374166,0.765811,0.368782,3.316625,0.500000,0.400000,0.500000,2.000000,2.000000,8.000000,3.000000,9.000000,2.000000,8.000000,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000,0.000000,0.000000,0.900000,0.600000,1.000000,11.000000,1.000000,0.000000,0.000000,1.000000,11.000000,1.000000,1.000000,2.000000,1.000000,93.000000,3.000000,0.400000,0.906190,0.396485,3.605551,0.700000,0.700000,0.700000,3.000000,3.000000,9.000000,4.000000,10.000000,3.000000,10.000000,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,13.000000,1.000000,1.000000,1.000000,0.900000,1.800000,4.037945,11.000000,1.000000,1.000000,9.000000,1.000000,17.000000,1.000000,1.000000,4.000000,2.000000,104.000000,3.000000,1.264911,3.720626,0.636396,3.741657,0.900000,0.900000,0.900000,5.000000,6.000000,10.000000,9.000000,12.000000,7.000000,25.000000,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
#unique values of each column of the data
for i in Data:
    print(f"                             {i.title()}                      ")
    print(f"* The number of unique values in {i} column :",Data[i].nunique())
    print(">>",Data[i].unique())
    print('==================================================================================')

                             Target
* The number of unique values in target column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_01
* The number of unique values in ps_ind_01 column : 8
>> [2 1 5 0 4 3 6 7]
==================================================================================
                             Ps_Ind_02_Cat
* The number of unique values in ps_ind_02_cat column : 5
>> [ 2  1  4  3 -1]
==================================================================================
                             Ps_Ind_03
* The number of unique values in ps_ind_03 column : 12
>> [ 5  7  9  2  0  4  3  1 11  6  8 10]
==================================================================================
                             Ps_Ind_04_Cat
* The number of unique values in ps_ind_04_cat column : 3
>> [ 1  0 -1]
==================================================================================
                             Ps_Ind_05_Cat
* The number of unique values in ps_ind_05_cat column : 8
>> [ 0  1  4  3  6  5 -1  2]
==================================================================================
                             Ps_Ind_06_Bin
* The number of unique values in ps_ind_06_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_07_Bin
* The number of unique values in ps_ind_07_bin column : 2
>> [1 0]
==================================================================================
                             Ps_Ind_08_Bin
* The number of unique values in ps_ind_08_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_09_Bin
* The number of unique values in ps_ind_09_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_10_Bin
* The number of unique values in ps_ind_10_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_11_Bin
* The number of unique values in ps_ind_11_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_12_Bin
* The number of unique values in ps_ind_12_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_13_Bin
* The number of unique values in ps_ind_13_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_14
* The number of unique values in ps_ind_14 column : 5
>> [0 1 2 3 4]
==================================================================================
                             Ps_Ind_15
* The number of unique values in ps_ind_15 column : 14
>> [11  3 12  8  9  6 13  4 10  5  7  2  0  1]
==================================================================================
                             Ps_Ind_16_Bin
* The number of unique values in ps_ind_16_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Ind_17_Bin
* The number of unique values in ps_ind_17_bin column : 2
>> [1 0]
==================================================================================
                             Ps_Ind_18_Bin
* The number of unique values in ps_ind_18_bin column : 2
>> [0 1]
==================================================================================
                             Ps_Reg_01
* The number of unique values in ps_reg_01 column : 10
>> [0.7 0.8 0.  0.9 0.6 0.5 0.4 0.3 0.2 0.1]
==================================================================================
                             Ps_Reg_02
* The number of unique values in ps_reg_02 column : 19
>> [0.2 0.4 0.  0.6 1.8 0.1 0.7 1.4 0.9 0.3 0.5 0.8 1.  1.3 1.6 1.5 1.2 1.1
 1.7]
==================================================================================
                             Ps_Reg_03
* The number of unique values in ps_reg_03 column : 5013
>> [ 0.71807033  0.76607767 -1.         ...  1.60078106  1.63075903
  1.74355958]
==================================================================================
                             Ps_Car_01_Cat
* The number of unique values in ps_car_01_cat column : 13
>> [10 11  7  6  9  5  4  8  3  0  2  1 -1]
==================================================================================
                             Ps_Car_02_Cat
* The number of unique values in ps_car_02_cat column : 3
>> [ 1  0 -1]
==================================================================================
                             Ps_Car_03_Cat
* The number of unique values in ps_car_03_cat column : 3
>> [-1  0  1]
==================================================================================
                             Ps_Car_04_Cat
* The number of unique values in ps_car_04_cat column : 10
>> [0 1 8 9 2 6 3 7 4 5]
==================================================================================
                             Ps_Car_05_Cat
* The number of unique values in ps_car_05_cat column : 3
>> [ 1 -1  0]
==================================================================================
                             Ps_Car_06_Cat
* The number of unique values in ps_car_06_cat column : 18
>> [ 4 11 14 13  6 15  3  0  1 10 12  9 17  7  8  5  2 16]
==================================================================================
                             Ps_Car_07_Cat
* The number of unique values in ps_car_07_cat column : 3
>> [ 1 -1  0]
==================================================================================
                             Ps_Car_08_Cat
* The number of unique values in ps_car_08_cat column : 2
>> [0 1]
==================================================================================
                             Ps_Car_09_Cat
* The number of unique values in ps_car_09_cat column : 6
>> [ 0  2  3  1 -1  4]
==================================================================================
                             Ps_Car_10_Cat
* The number of unique values in ps_car_10_cat column : 3
>> [1 0 2]
==================================================================================
                             Ps_Car_11_Cat
* The number of unique values in ps_car_11_cat column : 104
>> [ 12  19  60 104  82  99  30  68  20  36 101 103  41  59  43  64  29  95
  24   5  28  87  66  10  26  54  32  38  83  89  49  93   1  22  85  78
  31  34   7   8   3  46  27  25  61  16  69  40  76  39  88  42  75  91
  23   2  71  90  80  44  92  72  96  86  62  33  67  73  77  18  21  74
  37  48  70  13  15 102  53  65 100  51  79  52  63  94   6  57  35  98
  56  97  55  84  50   4  58   9  17  11  45  14  81  47]
==================================================================================
                             Ps_Car_11
* The number of unique values in ps_car_11 column : 5
>> [ 2  3  1  0 -1]
==================================================================================
                             Ps_Car_12
* The number of unique values in ps_car_12 column : 184
>> [ 0.4         0.31622777  0.37416574  0.31606961  0.44598206  0.44698993
  0.4472136   0.54772256  0.31527766  0.42426407  0.52915026  0.39987498
  0.40841156  0.38729833  0.42355637  0.4237924   0.36055513  0.39749214
  0.51961524  0.41797129  0.48989795  0.42201896  0.31559468  0.44586994
  0.39862263  0.56568542  0.64807407  0.39974992  0.59160798  0.47958315
  0.5         0.36878178  0.43588989  0.57445626  0.6164414   0.44710178
  0.31575307  0.44542115  0.6         0.39949969  0.54516053  0.39724048
  1.26491106  0.39937451  0.47539457  0.49769469  0.46882833  0.4240283
  0.66332496  0.33166248  0.51536395  0.69282032  0.44654227  0.37255872
  0.81853528  0.52896125  0.39899875  0.64791975  0.41231056  0.44687806
  0.39471509  0.43566042  0.46904158  0.49457052  0.66317419  0.38691084
  0.54607692  0.14142136  0.39962482  0.50049975  0.68563839  0.4241462
  0.53244718  0.4236744   0.6476882   0.39837169  0.60827625  0.63245553
  0.61465437  0.39433488  0.36041643  0.42178193  0.76811457  0.44553339
  0.44665423  0.39799497  0.46368092  0.65559134  0.46529561  0.63213923
  0.54580216  0.5105879   0.46593991  0.48487112  0.70469852  0.49939964
  0.52763624  0.52810984  0.678233    0.44384682  0.54644304  0.52848841
  0.3524202   0.44620623  0.49969991  0.6244998   0.60506198  0.3726929
  0.49949975  0.78740079  0.49979996  0.39522146  0.39812058  0.70710678
  0.69942834  0.47822589  0.72318739  0.54735729  0.54726593  0.4747631
  0.49929951  0.61571097  0.64031242  0.72111026  0.56559703  0.62609903
  0.6556676   0.62498     0.75498344  0.46518813  0.50990195  0.54424259
  0.58309519  0.28284271  0.48        0.39874804  0.64799691  0.74161985
  0.48518038  0.41964271  0.64591021  0.48969378  0.38639358  0.54378304
  0.44676616  0.46432747  0.17320508  0.62912638  0.77278716  0.70092796
  0.44418465  0.54662601  0.3088689   0.5745433   0.53851648  0.52905576
  0.54744863  0.63976558  0.64776539  0.49638695  0.42825226  0.54470175
  0.39761791  0.64007812  0.49568135 -1.          0.35199432  0.58120564
  0.78102497  0.56249444  0.39560081  0.65574385  0.36        0.53786615
  0.52640289  0.59143892  0.63087241  0.37040518  0.67082039  0.47906158
  0.1         0.14832397  0.34641016  0.70519501]
==================================================================================
                             Ps_Car_13
* The number of unique values in ps_car_13 column : 70482
>> [0.88367892 0.61881652 0.64158572 ... 1.58527574 0.96169455 1.56191797]
==================================================================================
                             Ps_Car_14
* The number of unique values in ps_car_14 column : 850
>> [ 0.37080992  0.38871583  0.34727511  0.29495762  0.36510273  0.40620192
  0.36878178  0.3748333   0.40743098  0.39025633  0.42953463  0.37934153
  0.38509739  0.35608988  0.35832946  0.5329165   0.34985711  0.3207803
  0.36633318  0.36124784  0.37027017  0.36837481  0.40137264  0.41291646
  0.52773099  0.4         0.44158804  0.38209946  0.36152455  0.38170669
  0.37682887  0.39076847  0.30740852  0.36193922  0.38262253  0.35986108
  0.39749214  0.40865633  0.36851052  0.38729833  0.28879058 -1.
  0.3468429   0.31032241  0.37549967  0.32878564  0.32924155  0.38548671
  0.33867388  0.37802116  0.37456642  0.41545156  0.43497126  0.41593269
  0.52048055  0.35        0.31937439  0.33763886  0.39370039  0.33166248
  0.34568772  0.39874804  0.38144462  0.37947332  0.35566838  0.30033315
  0.29916551  0.50576674  0.3744329   0.38236109  0.36578682  0.33090784
  0.32        0.36496575  0.49497475  0.34351128  0.36262929  0.38026307
  0.42661458  0.34438351  0.44586994  0.38600518  0.32787193  0.40938979
  0.43011626  0.37040518  0.41665333  0.39433488  0.30083218  0.4180909
  0.36331804  0.32557641  0.56568542  0.33075671  0.31304952  0.44497191
  0.37841776  0.31144823  0.34088121  0.32480764  0.38496753  0.42790186
  0.48579831  0.30495901  0.38078866  0.38483763  0.37107951  0.4189272
  0.42696604  0.46797436  0.39051248  0.40236799  0.32695565  0.37013511
  0.43069711  0.34496377  0.3866523   0.38196859  0.36400549  0.39912404
  0.41509035  0.35213634  0.32403703  0.42308392  0.40841156  0.39862263
  0.4110961   0.39937451  0.29444864  0.39        0.44609416  0.41412558
  0.47434165  0.40174619  0.500999    0.35425979  0.43634848  0.4669047
  0.32863353  0.28982753  0.39306488  0.32893768  0.38613469  0.36674242
  0.3324154   0.41472883  0.34205263  0.36660606  0.40533936  0.3057777
  0.39268308  0.42461747  0.35454196  0.37881394  0.3144837   0.35355339
  0.38691084  0.40099875  0.41653331  0.46151923  0.30708305  0.48414874
  0.33615473  0.42930176  0.36013886  0.428369    0.39179076  0.34885527
  0.44407207  0.3591657   0.35071356  0.35042831  0.38935845  0.37349699
  0.30199338  0.40348482  0.39089641  0.45497253  0.44777226  0.30166206
  0.5186521   0.30331502  0.3391165   0.50049975  0.39319206  0.30413813
  0.40311289  0.41749251  0.39242834  0.43393548  0.41012193  0.37616486
  0.40162171  0.36742346  0.37749172  0.32015621  0.43        0.32572995
  0.41218928  0.39849718  0.52820451  0.39648455  0.43588989  0.33882149
  0.35860842  0.3660601   0.4236744   0.32664966  0.35888717  0.47010637
  0.4302325   0.39585351  0.42918527  0.36055513  0.36810325  0.41773197
  0.40459857  0.42544095  0.29529646  0.32249031  0.46529561  0.40249224
  0.31622777  0.39204592  0.50596443  0.38678159  0.46260134  0.36646964
  0.4347413   0.33689761  0.34597688  0.42190046  0.32140317  0.45055521
  0.3959798   0.32756679  0.32634338  0.37255872  0.33316662  0.33015148
  0.45110974  0.35341194  0.33406586  0.32710854  0.31968735  0.31859065
  0.42118879  0.42895221  0.53944416  0.44271887  0.35777088  0.31464265
  0.55677644  0.34669872  0.45276926  0.32496154  0.28809721  0.42860238
  0.44676616  0.38470768  0.38249183  0.33481338  0.35818989  0.30967725
  0.41048752  0.52915026  0.35707142  0.52297227  0.32046841  0.44102154
  0.39038443  0.3232646   0.26172505  0.43081318  0.29664794  0.34539832
  0.31906112  0.44899889  0.41448764  0.35496479  0.46043458  0.47328638
  0.32093613  0.39623226  0.38742741  0.41170378  0.38405729  0.39496835
  0.37161808  0.39382737  0.37148351  0.41761226  0.43531598  0.49759421
  0.41856899  0.42130749  0.33        0.38987177  0.38858718  0.45672749
  0.41964271  0.40049969  0.33045423  0.35972212  0.33151169  0.31811947
  0.32109189  0.39962482  0.36138622  0.36        0.48785244  0.37815341
  0.38832976  0.39724048  0.3241913   0.34117444  0.34176015  0.42083251
  0.34871192  0.29732137  0.37309516  0.42520583  0.43954522  0.5399074
  0.38535698  0.43988635  0.32984845  0.33030289  0.34423829  0.43185646
  0.30903074  0.34219877  0.38845849  0.3138471   0.41024383  0.42485292
  0.40987803  0.36414283  0.21095023  0.32171416  0.52134442  0.38327536
  0.3992493   0.33136083  0.33226495  0.39522146  0.4237924   0.41255303
  0.39115214  0.31400637  0.3471311   0.3910243   0.44440972  0.43852024
  0.53009433  0.40521599  0.42684892  0.43703547  0.39698866  0.36166283
  0.43116122  0.36959437  0.56833089  0.29832868  0.37215588  0.51283526
  0.32848135  0.37894591  0.2         0.31733263  0.39987498  0.36783148
  0.38340579  0.53619026  0.34554305  0.35468296  0.42426407  0.29410882
  0.43829214  0.4224926   0.50675438  0.42720019  0.42320208  0.34058773
  0.37242449  0.3132092   0.2236068   0.40472213  0.37854986  0.39812058
  0.50249378  0.39012818  0.38157568  0.36083237  0.39344631  0.33808283
  0.34044089  0.47853944  0.40224371  0.32124757  0.40496913  0.33585711
  0.49396356  0.45880279  0.3354102   0.41833001  0.39331921  0.48062459
  0.33466401  0.45628938  0.43749286  0.42071368  0.32186954  0.45978256
  0.3342155   0.36592349  0.30870698  0.5205766   0.34741906  0.28372522
  0.40261644  0.47749346  0.1183216   0.32465366  0.52345009  0.56656862
  0.41713307  0.36769553  0.32680269  0.34249088  0.39635842  0.48332184
  0.40570926  0.40804412  0.20976177  0.42011903  0.38457769  0.53197744
  0.38366652  0.3508561   0.34899857  0.37469988  0.42107007  0.44665423
  0.48476799  0.3         0.3082207   0.31352831  0.40274061  0.39837169
  0.36537652  0.54954527  0.31701735  0.38561639  0.32939338  0.34452866
  0.43416587  0.42567593  0.35721142  0.44384682  0.31064449  0.35185224
  0.35014283  0.34641016  0.41904654  0.42602817  0.39408121  0.36469165
  0.43208795  0.30610456  0.39761791  0.42778499  0.41916584  0.39887341
  0.4419276   0.42166337  0.40435133  0.37735925  0.34132096  0.33555923
  0.37282704  0.36565011  0.41352146  0.32969683  0.41231056  0.41303753
  0.46335731  0.42532341  0.34278273  0.38704005  0.36373067  0.405586
  0.36386811  0.57532599  0.13601471  0.34292856  0.34394767  0.42449971
  0.47539457  0.5417564   0.30659419  0.52249402  0.4384062   0.36097091
  0.42743421  0.4039802   0.49598387  0.41581246  0.5105879   0.23323808
  0.37416574  0.45166359  0.28722813  0.37        0.37656341  0.46314145
  0.41952354  0.31953091  0.55226805  0.30773365  0.40062451  0.40124805
  0.45639895  0.5286776   0.43162484  0.43046486  0.27748874  0.53244718
  0.35958309  0.44463468  0.45033321  0.34928498  0.3176476   0.45825757
  0.34234486  0.42284749  0.36986484  0.45343136  0.41243181  0.40373258
  0.41928511  0.43197222  0.29325757  0.49799598  0.53478968  0.35749126
  0.34467376  0.50199602  0.45243784  0.44045431  0.35637059  0.51117512
  0.3968627   0.37067506  0.49345719  0.32434549  0.59160798  0.33060551
  0.41036569  0.4241462   0.38131352  0.33600595  0.29257478  0.51961524
  0.49517674  0.40914545  0.46904158  0.43874822  0.464758    0.32062439
  0.38884444  0.35944402  0.53851648  0.430581    0.28284271  0.38275318
  0.43127717  0.55407581  0.3764306   0.38013156  0.46368092  0.44090815
  0.24899799  0.36290495  0.33496268  0.51185936  0.31527766  0.35312887
  0.32741411  0.45607017  0.54405882  0.4577117   0.47979162  0.42343831
  0.49879856  0.51652686  0.47927028  0.34785054  0.58309519  0.52105662
  0.3720215   0.47222876  0.33734256  0.41797129  0.39774364  0.31921779
  0.38923001  0.41533119  0.34409301  0.44977772  0.50149776  0.3691883
  0.27386128  0.46850827  0.3485685   0.31654384  0.23345235  0.35171011
  0.41821047  0.63166447  0.45022217  0.38794329  0.28635642  0.53103672
  0.40484565  0.37363083  0.32802439  0.4472136   0.51768716  0.33361655
  0.38091994  0.4428318   0.37296112  0.45265881  0.38961519  0.35284558
  0.26457513  0.48887626  0.3630427   0.33778692  0.30805844  0.44022721
  0.44068129  0.4494441   0.55045436  0.35846897  0.43289722  0.36180105
  0.42154478  0.40187063  0.33793491  0.41785165  0.40087405  0.33749074
  0.39140772  0.54267854  0.40669399  0.35142567  0.30561414  0.4769696
  0.33985291  0.35623026  0.33391616  0.43358967  0.29512709  0.44888751
  0.43817805  0.45464272  0.34626579  0.35679126  0.6363961   0.53385391
  0.50358713  0.42731721  0.38974351  0.23021729  0.38418745  0.36221541
  0.33376639  0.44833024  0.37134889  0.4501111   0.44799554  0.45332108
  0.10954451  0.48631266  0.30066593  0.498999    0.45199558  0.32726136
  0.45221676  0.43646306  0.49699095  0.33955854  0.22135944  0.32603681
  0.43669211  0.43943145  0.46540305  0.3726929   0.53665631  0.34799425
  0.39293765  0.37603191  0.55090834  0.4330127   0.55136195  0.34583233
  0.3481379   0.55901699  0.55497748  0.46583259  0.59581876  0.28600699
  0.48373546  0.33211444  0.33837849  0.34365681  0.39534795  0.48928519
  0.3798684   0.47623524  0.31112698  0.52678269  0.38392708  0.3548239
  0.45814845  0.37536649  0.46421978  0.47275787  0.52725705  0.49648766
  0.22315914  0.35099858  0.55452683  0.45934736  0.30854497  0.44362146
  0.32649655  0.4620606   0.31827661  0.28827071  0.47        0.39560081
  0.21794495  0.41073106  0.3215587   0.47381431  0.31749016  0.52153619
  0.40681691  0.50497525  0.45716518  0.56595053  0.4482187   0.56035703
  0.43243497  0.50547008  0.32817678  0.23452079  0.32264532  0.52440442
  0.53525695  0.51691392  0.54863467  0.31780497  0.38587563  0.50714889
  0.45387223  0.41146081  0.4748684   0.48989795  0.37403208  0.42473521
  0.2078461   0.42976738  0.36551334  0.44687806  0.57445626  0.57008771
  0.39572718  0.38353618  0.40975603  0.28548205  0.56124861  0.22427661
  0.48166378  0.40926764  0.56789083  0.2792848   0.49949975  0.43772137
  0.49446941  0.49678969  0.47159304  0.46173586  0.43543082  0.33570821
  0.48135226  0.50398413  0.54313902  0.31256999  0.4348563   0.54543561
  0.3906405   0.44553339  0.30248967  0.45912961  0.44124823  0.54350713

In [17]:
#check the value count of all the column in the data
for i in Data:
    print(f"                             {i.title()}                      ")
    print(Data[i].value_counts())
    print('==================================================================================')

                             Target
target
0    573518
1     21694
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_01
ps_ind_01
0    187594
1    143984
2     82468
5     61464
3     51193
4     33524
6     17682
7     17303
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_02_Cat
ps_ind_02_cat
 1    431859
 2    123573
 3     28186
 4     11378
-1       216
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_03
ps_ind_03
2     96110
3     81973
1     67994
4     67213
5     62803
6     60406
7     52364
8     39667
9     25436
0     15514
10    14484
11    11248
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_04_Cat
ps_ind_04_cat
 0    346965
 1    248164
-1        83
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_05_Cat
ps_ind_05_cat
 0    528009
 6     20662
 4     18344
 1      8322
 3      8233
-1      5809
 2      4184
 5      1649
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_06_Bin
ps_ind_06_bin
0    360852
1    234360
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_07_Bin
ps_ind_07_bin
0    442223
1    152989
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_08_Bin
ps_ind_08_bin
0    497644
1     97568
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_09_Bin
ps_ind_09_bin
0    484917
1    110295
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_10_Bin
ps_ind_10_bin
0    594990
1       222
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_11_Bin
ps_ind_11_bin
0    594205
1      1007
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_12_Bin
ps_ind_12_bin
0    589594
1      5618
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_13_Bin
ps_ind_13_bin
0    594648
1       564
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_14
ps_ind_14
0    588832
1      5495
2       744
3       136
4         5
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_15
ps_ind_15
7     65336
8     59600
6     58408
10    54341
11    53215
9     45497
12    44851
5     42553
4     41770
13    35256
3     32267
0     31826
2     18675
1     11617
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_16_Bin
ps_ind_16_bin
1    393330
0    201882
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_17_Bin
ps_ind_17_bin
0    523143
1     72069
Name: count, dtype: int64
==================================================================================
                             Ps_Ind_18_Bin
ps_ind_18_bin
0    503879
1     91333
Name: count, dtype: int64
==================================================================================
                             Ps_Reg_01
ps_reg_01
0.9    194608
0.7     67897
0.8     60277
0.6     56243
0.4     53569
0.1     43192
0.3     40290
0.5     32341
0.2     25113
0.0     21682
Name: count, dtype: int64
==================================================================================
                             Ps_Reg_02
ps_reg_02
0.2    114886
0.3     95033
0.0     89297
0.4     59746
0.5     36528
0.6     33474
0.1     31816
0.7     21210
0.8     19907
0.9     16788
1.2     15843
1.0     12570
1.3     11761
1.1     11321
1.4      6877
1.5      5845
1.6      5095
1.8      4737
1.7      2478
Name: count, dtype: int64
==================================================================================
                             Ps_Reg_03
ps_reg_03
-1.000000    107772
 0.633936       664
 0.602599       637
 0.704894       627
 0.587899       616
              ...
 1.863632         1
 1.612645         1
 1.600781         1
 1.630759         1
 1.743560         1
Name: count, Length: 5013, dtype: int64
==================================================================================
                             Ps_Car_01_Cat
ps_car_01_cat
 11    207573
 7     179247
 6      62393
 10     50087
 4      26174
 9      20323
 5      18142
 8      15093
 3       6658
 0       5904
 2       2144
 1       1367
-1        107
Name: count, dtype: int64
==================================================================================
                             Ps_Car_02_Cat
ps_car_02_cat
 1    493990
 0    101217
-1         5
Name: count, dtype: int64
==================================================================================
                             Ps_Car_03_Cat
ps_car_03_cat
-1    411231
 1    110709
 0     73272
Name: count, dtype: int64
==================================================================================
                             Ps_Car_04_Cat
ps_car_04_cat
0    496581
1     32115
2     23770
8     20598
9     19034
6      1560
3       640
5       545
4       230
7       139
Name: count, dtype: int64
==================================================================================
                             Ps_Car_05_Cat
ps_car_05_cat
-1    266551
 1    172667
 0    155994
Name: count, dtype: int64
==================================================================================
                             Ps_Car_06_Cat
ps_car_06_cat
11    131527
1     118386
0     110420
14     59253
10     33466
4      31136
15     21732
6      20951
9      17617
7      16158
3      11997
13      6246
17      4935
16      4582
12      2386
2       1607
8       1412
5       1401
Name: count, dtype: int64
==================================================================================
                             Ps_Car_07_Cat
ps_car_07_cat
 1    553148
 0     30575
-1     11489
Name: count, dtype: int64
==================================================================================
                             Ps_Car_08_Cat
ps_car_08_cat
1    495264
0     99948
Name: count, dtype: int64
==================================================================================
                             Ps_Car_09_Cat
ps_car_09_cat
 2    353482
 0    194518
 1     29080
 3     14756
 4      2807
-1       569
Name: count, dtype: int64
==================================================================================
                             Ps_Car_10_Cat
ps_car_10_cat
1    590179
0      4857
2       176
Name: count, dtype: int64
==================================================================================
                             Ps_Car_11_Cat
ps_car_11_cat
104    85083
103    24262
64     22278
87     17106
32     12578
       ...
58      1464
81      1433
56      1272
18      1233
63      1103
Name: count, Length: 104, dtype: int64
==================================================================================
                             Ps_Car_11
ps_car_11
 3    318919
 2    189353
 1     60952
 0     25983
-1         5
Name: count, dtype: int64
==================================================================================
                             Ps_Car_12
ps_car_12
0.316228    170579
0.400000    111873
0.374166     98598
0.447214     49318
0.424264     49293
             ...
0.370405         1
0.670820         1
0.479062         1
0.346410         1
0.705195         1
Name: count, Length: 184, dtype: int64
==================================================================================
                             Ps_Car_13
ps_car_13
0.674583    386
0.741689    377
0.692776    363
0.841781    362
0.749228    353
           ...
0.877702      1
0.815507      1
1.585276      1
0.961695      1
1.561918      1
Name: count, Length: 70482, dtype: int64
==================================================================================
                             Ps_Car_14
ps_car_14
-1.000000    42620
 0.361525    17696
 0.358329    15523
 0.361939    11885
 0.368782    11626
             ...
 0.416773        1
 0.414608        1
 0.403856        1
 0.423320        1
 0.511371        1
Name: count, Length: 850, dtype: int64
==================================================================================
                             Ps_Car_15
ps_car_15
3.605551    109765
3.464102     77200
3.316625     68737
3.162278     63323
3.741657     57757
2.828427     48680
3.000000     48537
2.645751     30388
2.449490     20445
2.236068     19397
0.000000     14186
2.000000     12830
1.732051     10744
1.000000      6708
1.414214      6515
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_01
ps_calc_01
0.6    59837
0.0    59780
0.8    59710
0.5    59612
0.7    59545
0.2    59513
0.1    59504
0.3    59377
0.4    59248
0.9    59086
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_02
ps_calc_02
0.5    60070
0.4    59823
0.0    59618
0.3    59593
0.7    59502
0.6    59501
0.2    59385
0.1    59383
0.9    59219
0.8    59118
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_03
ps_calc_03
0.1    60036
0.5    59832
0.3    59819
0.6    59521
0.8    59509
0.9    59418
0.7    59393
0.0    59318
0.4    59229
0.2    59137
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_04
ps_calc_04
2    193977
3    175512
1    108012
4     79606
0     23912
5     14193
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_05
ps_calc_05
2    195160
1    170860
3    119192
0     61226
4     40682
5      7534
6       558
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_06
ps_calc_06
8     175015
7     139771
9     129207
6      73478
10     43085
5      26613
4       6705
3       1199
2        132
1          6
0          1
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_07
ps_calc_07
3    162414
2    139101
4    122039
1     69309
5     61705
6     20403
0     15290
7      4381
8       547
9        23
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_08
ps_calc_08
9     151746
10    151330
8     102944
11     91639
7      49567
12     25392
6      17183
5       4469
4        842
3         90
2         10
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_09
ps_calc_09
2    182519
3    152829
1    121391
4     76973
0     34479
5     22976
6      3782
7       263
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_10
ps_calc_10
8     82043
7     78009
9     76772
10    65307
6     64567
11    49566
5     46181
12    34914
4     27204
13    22709
14    13694
3     12981
15     7701
2      4566
16     4110
17     2041
1      1107
18      922
19      401
20      168
0       139
21       65
22       33
23       10
25        1
24        1
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_11
ps_calc_11
5     102512
4      93890
6      93110
7      72148
3      69519
8      49105
2      38364
9      29827
10     16233
1      14035
11      7928
12      3583
0       2461
13      1575
14       631
15       189
16        68
17        22
18        11
19         1
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_12
ps_calc_12
1     203280
2     145321
0     141001
3      70351
4      25778
5       7290
6       1724
7        387
8         66
9         11
10         3
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_13
ps_calc_13
2     139334
3     132412
1      96661
4      95753
5      54560
0      33658
6      26326
7      11003
8       3882
9       1160
10       351
11        88
12        20
13         4
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_14
ps_calc_14
7     86673
8     82177
6     80897
9     68487
5     64029
10    52049
4     42596
11    35341
3     22825
12    22227
13    12883
2      8942
14     6934
15     3536
1      2398
16     1666
17      735
0       310
18      305
19      131
20       47
21       18
22        5
23        1
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_15_Bin
ps_calc_15_bin
0    522342
1     72870
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_16_Bin
ps_calc_16_bin
1    373698
0    221514
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_17_Bin
ps_calc_17_bin
1    329856
0    265356
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_18_Bin
ps_calc_18_bin
0    424278
1    170934
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_19_Bin
ps_calc_19_bin
0    387469
1    207743
Name: count, dtype: int64
==================================================================================
                             Ps_Calc_20_Bin
ps_calc_20_bin
0    503955
1     91257
Name: count, dtype: int64
==================================================================================